sonar.projectKey=Taher2512_gitops-k8s-platform
sonar.organization=taher2512
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.qualitygate.wait=false